### ISSUE TITLE
Border color only

### ISSUE THREAD

**Issue by Christilut** [jgclark/vscode-todo-highlight#13]
This is a problem I've had with the original extension for a long time. I'd like the border of a line to be colored, but keep the original text color.
Right now the text becomes white when I turn the text color off with a border.

Can this version help there?

**Comment by jgclark** [comment]
Hmm, this is an interesting one.  I've had a go myself and it seems to do the same: add the border OK, but changes the colour of the text within it to an unexpected colour.

Please can you post the `"todohighlight.keywords": ...` and `` parts of your configuration, and which keyword trigger you're using? And are you using a dark or a light theme?  I can then have a go.

**Comment by Christilut** [comment]
Here's my full config:
```
  "todohighlight.isEnable": true,
  "todohighlight.keywords": [
    {
      "text": "NOTE:",
      "color": "#ff0000",
      "backgroundColor": "white",
      "overviewRulerColor": "grey"
    },
    {
      "text": "TEMP:",
      "color": "#c98436",
      "backgroundColor": "transparent",
      "border": "1px solid #ff8800",
      "isWholeLine": true,
      "overviewRulerColor": "#ff8800"
    },
    {
      "text": "TODO:",
      "color": "white",
      "backgroundColor": "#ff00ff",
      "overviewRulerColor": "#ff00ff"
    }
  ],
  "todohighlight.isCaseSensitive": false,
  "todohighlight.defaultStyle": {
    "color": "white",
    "backgroundColor": "#ff00ff",
    "overviewRulerColor": "pink",
    "borderRadius": "2px",
    "cursor": "pointer",
    "border": "none",
    "isWholeLine": false
  },
  "todohighlight.include": [
    "**/*.js",
    "**/*.jsx",
    "**/*.ts",
    "**/*.tsx",
    "**/*.html",
    "**/*.php",
    "**/*.css",
    "**/*.scss",
    "**/*.vue"
  ],
  "todohighlight.exclude": [
    "**/node_modules/**",
    "**/bower_components/**",
    "**/dist/**",
    "**/build/**",
    "**/.vscode/**",
    "**/.github/**",
    "**/_output/**",
    "**/*.min.*",
    "**/*.map",
    "**/.next/**"
  ],
  "todohighlight.maxFilesForSearch": 5120,
  "todohighlight.toggleURI": false,
```

The keyword in question is the `TEMP:` one. Now it does orange text & border but I'd like it to be only orange border but intellisensed text color.
I'm using the Dark+ theme.

Thanks!

**Comment by jgclark** [comment]
OK, I think we're narrowing down the issue. I've realised there are three different ways text can be coloured here:
1. the label itself (e.g. "TEMP:")
2. any other text included in a regex term
3. the whole line, if `isWholeLine` is set to `true`.

I think you're hitting problems on type 3, which I can reproduce. Even if you take out the `"color": "#c98436"` from the keyword and the ` "color": "white"` from the defaultStyle, it doesn't render other intellisense colours, but makes all the text on the line blue, whatever the theme in use.

I've tracked down this blue in the code, I think to util.js line 26 in the definition of DEFAULT_STYLE, and also in extension.js.  Sadly, though, as I didn't write any of this code, and hardly know Javascript, I can't understand the main extension.js code, so can't fix this.

**Comment by Christilut** [comment]
Thanks for trying! I have zero extension experience so I can't really help here

**Comment by zerefdev** [comment]
set color to empty string
```json
    {
      "text": "TEMP:",
      "color": "",
      "backgroundColor": "transparent",
      "border": "1px solid #ff8800",
      "isWholeLine": true,
      "overviewRulerColor": "#ff8800"
    }
```

**Comment by Christilut** [comment]
Thanks! That actually works perfect!
