### ISSUE TITLE
Mark this as a successor

### ISSUE THREAD

**Issue by yaSebastian** [jgclark/vscode-todo-highlight#16]
Hi,

thanks for taking over maintaining this extension.

When preparing the VS Code extension recommendations for my team, I ran into the issue of two seemingly identical versions of this extension existing on the Visual Studio Marketplace. When searching for it in VS Code, the outdated version is on place one and this one on place four, so I am pretty sure people are still installing the older version, certainly in my team as well.

On a first glance, this version seems just like a copy of the unmaintained original, also, it has not been forked via the GitHub fork feature, so no connection is shown there.
Only when you scroll down in the README.md, you can find some information about this being a fork and the reason behind it. On VS Marketplace you can not see any information about that at all.

Had I been in a hurry, I would have installed the outdated version as well, as a consequence.

To contribute to others not doing the same and promoting this version, I opened [Issue #187 on the outdated repository](https://github.com/wayou/vscode-todo-highlight/issues/187), asking one of the contributors to update the README.md there, so that it points to this repository.

In addition, I would suggest for the README.md of this project, as well as the VS Marketplace site to shorten the history chapter and move it to the top, e.g. like this:
> This extension was [started and maintained by **wayou**](https://github.com/wayou/vscode-todo-highlight) until 2018. [**jgclark**](https://github.com/jgclark) then picked it up in mid-2020, as the original extension was no longer maintained. See CHANGELOG.md for more details.

Cheers

**Comment by jgclark** [comment]
Many thanks, @yaSebastian, for your kind words and suggestion.
I doubt the outdated repository will get updated, but there's no harm in trying.
I've done what I can, and updated the README as you suggest (commit 8648492399375f99b84e97e6ff404f71534afba3), and pushed that to the marketplace. I've kept the same version number as the code and functionality is no different.

**Comment by yaSebastian** [comment]
> I doubt the outdated repository will get updated, but there's no harm in trying.
Exactly my thought.
Thanks for the update.
