### ISSUE TITLE
Pattern not working

### ISSUE THREAD

**Issue by adamreisnz** [jgclark/vscode-todo-highlight#18]
I am using the regex pattern option exactly as per the example, but it doesn't seem to work.
When I only specify a regex, it doesn't match anything. When I add the text, it will match, but then it doesn't respect the regex.

The example in the readme specifies both a text and regex, but that doesn't seem to be the way.

![image](https://user-images.githubusercontent.com/490562/107143064-c15ce180-6997-11eb-9860-97e8d213bbc4.png)

Compare:

![image](https://user-images.githubusercontent.com/490562/107143080-e0f40a00-6997-11eb-9c34-0ab92c0adaad.png)

See how DENOTE: is still matched.

**Comment by jgclark** [comment]
I've checked the example in the README, and it's working OK for me still.
In your screenshot I can see the DENOTE: highlight is in red, which makes me think its matching on a different keyword definition, not the one shown. Please can you check?

PS I agree having both the `"text"` and `"regex"` in the keyword definition is a bit strange. I didn't write it!

**Comment by adamreisnz** [comment]
Ok looks like false alarm, I think the v1 extension, even though I had disabled and removed it, was still active in memory and conflicting with the new version.

After a restart it appears to be working 👍
