### ISSUE TITLE
Highlighting colors are greyed out

### ISSUE THREAD

**Issue by frankicia** [jgclark/vscode-todo-highlight#23]
When changing to a new tab, highlighted words are the correct color. But, after a short time the color is greyed out for all words.

An example is probably better:
After a short time (really short,  I cannot take a picture before it changes :( ):
![image](https://user-images.githubusercontent.com/2611796/125079362-cc8d7800-e0c3-11eb-89de-7ec84bc048eb.png)

The before, would be with all the word with the same highlighted color than the colons

**Comment by jgclark** [comment]
That's odd.
It's most likely that something else is interfering with the text, as it sounds like its rendering correctly to start with.
To narrow this down, I suggest you try disabling other extensions -- perhaps using VSCode's built-in bisecting method. Try this in other languages etc.

**Comment by jgclark** [comment]
Please re-open if you find this is down to this plugin.
