### ISSUE TITLE
Add complete settings autocompletion for before and regex

### ISSUE THREAD

**Issue by alkatar21** [jgclark/vscode-todo-highlight#29]
While `regex` shows up in the list, `before` does not.
I don't know if these can have more than the one argument?
- If not I would also suggest omitting the curly braces with an extra argument.
- If there are more than one, autocompletion would be desirable here as well.

**Comment by jgclark** [comment]
Thanks. I've now investigated this further, and improved the documentation for this (already live).
In the next release there will be autocompletion.
But the {...} need to stay as that's part of the syntax that VSCode defines.
