### ISSUE TITLE
RegEx pattern of the "NOTE" example ist not working for me.

### ISSUE THREAD

**Issue by gitarian** [jgclark/vscode-todo-highlight#3]
Hi Jonathan,

first of all, thank you for continuing this extension!

In my case (VS Code1.47.2 and  TODO Highlight 1.21) your example for the "NOTE" regex is not working (nothing gets highlighted at all).

```
 "regex": {
       "pattern": "(?<=^|\\\\s)NOTE[:]?" // in this example, highlight `NOTE:` with or without the `:` and that's not part of another word.  (I.e.: The above will highlight 'NOTE' but not the "note" in 'SIDENOTE').
        /**
         * NOTE: remember to escapse the backslash if there's any in your regexp (using \\\\ instead of single backslash)"
         * Positive lookbehind (`(?<=...)`) is only supported in Node.js v9 and up.
         * If your VSCode version is built on an earlier version the example above may not work.
         * bynoted byNOTE NOTEing NOTE:
         **/
},
```
\
\
Like with Textmate rules two backslashes are sufficient, better: exactly what is required - at least on my side (the first one is needed to let the 2nd one survive the processing before the rule is passed to the regex engine.
Additionally, the "[:]?" part will not exclude "NOTEing" from being marked because it doesn't differentiate any further the case where the terminal colon is missing.

Here ist what's working for me.
```
"regex": {
  "pattern": "(?<=^|\\s)NOTE[:]?(?!\\w)"
```

**Comment by gitarian** [comment]
Update to support the string literal in the `settings.json` as well.

`(?<=^|\"|\\s)NOTE[:]?(?!\\w)`

**Comment by jgclark** [comment]
I'm not sure why it works for me and not for you.
However, I've tried making those changes to the README, and published a new .vsix for you to test: 
https://github.com/jgclark/vscode-todo-highlight/blob/master/vscode-todo-highlight-1.2.2.vsix
If that's OK I can include in a next marketplace release.

**Comment by gitarian** [comment]
I'm embarrassed that I have to say I don't know what exactly to do with this .vsix-file (I've installed VS Code for the very first time just some days ago).
How do I add it to my installation? Does the existing extension from the marketplace interfere with this version (so I have to uninstall it)?

After you wrote that it IS working for you I made a another fresh VSCode install with just your extension. Et voilà: the original regex is working.
Either my installation is "screwed" or some other extension is coming into play.

Since I will have some days off with the family I suppose it's better to wait anyway? I could offer to rebuild my current VSCode setup extension-by-extension to find the possible root cause.

**Comment by jgclark** [comment]
Well, I'm happy to say your code does seem to be an improvement, and it is working for me. So it's worth you testing it. To do that:
1. in VSC go to the Extensions pane, and in the top right corner under the '...' menu there's an option to "Install from VSIX ...". Use this to point it to the new 1.2.2 version of the `.vsix` package.
2. re-load VSC to active the new extension.

Does that continue to work for you?

**Comment by gitarian** [comment]
Thanks for the installations steps.

After doing that it looks like this:

![TD_highlight_1](https://user-images.githubusercontent.com/24372132/89094810-574ff800-d3c8-11ea-8f5f-88fa6fc0d48b.png)

And in a "real" comment snippet:
![TD_highlight_2](https://user-images.githubusercontent.com/24372132/89094827-6b93f500-d3c8-11ea-8e90-c93a0948f82f.png)

Seems good, I think. Thanks!

**Comment by jgclark** [comment]
Very nice!
I will close this and issue a new release to the marketplace soon.
