### ISSUE TITLE
Show all defaults in the config

### ISSUE THREAD

**Issue by alkatar21** [jgclark/vscode-todo-highlight#31]
The default values of `todohighlight.defaultStyle` and `todohighlight.keywords` are not taken over into the config when you select them (so they are not in the default config). At least VSCode settings do. Currently you have to look them up in the code. Maybe they are just missing in the `package.json`?
(I am not sure if they could then be removed from the code, although that could probably be another Issue).

**Comment by jgclark** [comment]
Good suggestion, thanks.

**Comment by alkatar21** [comment]
Since I don't program JS myself and have no idea about VSCode extensions, I can't test it myself, but maybe only the following is missing:
https://github.com/jgclark/vscode-todo-highlight/blob/6b10ef6d5f96af9ce5fd1bf9019ad8c1f6531daa/package.json#L156
```json
"default": {
    "color": "#2196f3",
    "backgroundColor": "#ffeb3b",
}
```

und in https://github.com/jgclark/vscode-todo-highlight/blob/6b10ef6d5f96af9ce5fd1bf9019ad8c1f6531daa/package.json#L107
```json
"default": {
    "TODO:": {
        "text": "TODO:",
        "color": "#fff",
        "backgroundColor": "#ffbd2a",
        "overviewRulerColor": "rgba(255,189,42,0.8)"
    },
    "FIXME:": {
        "text": "FIXME:",
        "color": "#fff",
        "backgroundColor": "#f06292",
        "overviewRulerColor": "rgba(240,98,146,0.8)"
    }
}
```

**Comment by jgclark** [comment]
I've tried this out, and it doesn't work. 
That part of the package.json file is defining terms, and it can take a default values _inside_ the setting definition, but it only gets applied as a completion when a user edits that particular definition in settings.json.

**Comment by alkatar21** [comment]
Yes, it is correct that it is only transferred to `settings.json` when changes are made. This file should only contain changes that differ from the default. If these values are in the `defaultSettings.json` everything is correct, then it is the same as for other extensions and VSCode itself.

I had looked at the following https://github.com/microsoft/vscode-docker/blob/e2f0fa48901d086ae72e569d4c04d9ab37cd61a8/package.json#L1801. This is present in the `defaultSettings.json` and is therefore automatically transferred to the `settings.json` when the parameter is selected.

**Comment by alkatar21** [comment]
I think #62 is fixing this, so i will close the issue as completed.

They could now be removed from the code, although that is probably be a new issue
