### ISSUE TITLE
Enhancement: Improve Settings autocompletion and simplify regex in settings

### ISSUE THREAD

**Issue by alkatar21** [jgclark/vscode-todo-highlight#35]
After the release of version 2.0.4, I took a closer look at the extension.
Thanks here for the quick reply and the improvements.
Unfortunately, I currently have no time to set up JS myself and to learn to fix and improve things myself. Maybe in a few months time.

#29 was probably not really understandable and I had also made some wrong assumptions, therefore now again in more detail:
I understand now how it is done with the styles. In `todohighlight.defaultStyle` and also in `todohighlight.keywords` [DecorationRenderOptions](https://code.visualstudio.com/api/references/vscode-api#DecorationRenderOptions) are used for the style .
Additionally in `todohighlight.keywords` there is `text` and `regex` which is defined by itself.

With this knowledge it is true that `{...}` for "before" cannot be removed.

Currently, the autocompletion for this looks like this:
![grafik](https://user-images.githubusercontent.com/61387986/132223820-3f33112f-73a8-485c-aca6-fb889ebbf22b.png)![grafik](https://user-images.githubusercontent.com/61387986/132223715-cddd732e-0982-44d2-8341-939ca2be367c.png)

#### How could the completion be improved for the styles?
We could of course define all parts from `DecorationRenderOptions` in the `settings.json`. But I would suggest to extend the documentation and show only the most important options as now.
One possibility would be to extend the following descriptions and indicate that all options from [DecorationRenderOptions](https://code.visualstudio.com/api/references/vscode-api#DecorationRenderOptions) are possible:
https://github.com/jgclark/vscode-todo-highlight/blob/6b10ef6d5f96af9ce5fd1bf9019ad8c1f6531daa/package.json#L158 https://github.com/jgclark/vscode-todo-highlight/blob/6b10ef6d5f96af9ce5fd1bf9019ad8c1f6531daa/package.json#L110 Something like:
```json
"markdownDescription": "... Further options can be found [here](https://code.visualstudio.com/api/references/vscode-api#DecorationRenderOptions).",
```

#### `regex` property improve or simplify
A quick fix is to fix the `settings.json`, because currently regex is not defined correctly. The following should work, but would need to be tested:
https://github.com/jgclark/vscode-todo-highlight/blob/6b10ef6d5f96af9ce5fd1bf9019ad8c1f6531daa/package.json#L135
```diff
"regex": {
+   "type": "object",
-   "pattern": {
-       "type": "string",
-       "description": "The RegEx pattern to use for matching instead of the text value.REMEMBER to escape the backslash if there's any in your regexp (using \\\\ instead of single backslash)"
+   "properties": {
+       "pattern": {
+          "type": "string",
+          "description": "The RegEx pattern to use for matching instead of the text value.REMEMBER to escape the backslash if there's any in your regexp (using \\\\ instead of single backslash)"
+       } 
    }
},
```
But since `regex` is defined by us, I would suggest to simplify it permanently, since a new object for a single parameter makes little sense. This would then simplify in `settings.json` as follows, but also needs some code adjustments:
```diff
"regex": {
-   "pattern": {
-       "type": "string",
-       "description": "The RegEx pattern to use for matching instead of the text value.REMEMBER to escape the backslash if there's any in your regexp (using \\\\ instead of single backslash)"
-    }
+   "type": "string",
+   "description": "The RegEx pattern to use for matching instead of the text value.REMEMBER to escape the backslash if there's any in your regexp (using \\\\ instead of single backslash)"
},
```

**Comment by jgclark** [comment]
Thanks for the further analysis and suggestions, @alkatar21.

Completions: will try again with the additional completions (before, after, cursor). The links to the VSCode documentation was already in most of the descriptions.

Regex property: agreed that this could and should be simplified. The challenge is that it would be a breaking change for anyone who has used custom regexes. Do you have any suggestions about how to warn those users when they upgrade to this, apart from making the next version either 2.1.0 or 3.0.0?

**Comment by jgclark** [comment]
@alkatar21 I have now uploaded a candidate v2.0.5 vscode-todo-highlight-2.0.5.vsix file to the top level of this repo for you to test out, to see if the new completions work right for you.

**Comment by alkatar21** [comment]
This looks good so far. But there are a few small bugs. If desired, I could do a PR with a suggestion for a few more tweaks and for #31 as well. If you build this for me, I would test it.

**Comment by jgclark** [comment]
Please do, @alkatar21!

**Comment by alkatar21** [comment]
I think this is also completed now with #62. Or at least enough to close it for now.
