### ISSUE TITLE
Include and exclude options don't work

### ISSUE THREAD

**Issue by Acmion** [jgclark/vscode-todo-highlight#42]
Even if specifying `todohighlight.include = []` and `todohighlight.exclude = [ "**/*.* "]`, keywords still get highlighted in all files.

Maybe the issue is the fact that the inclusion and exclusion is not directly handled in the function `updateDecorations` in `src/extension.js`.

Perhaps adding something like this into the `updateDecorations` function will work:
```
// the function isFileNameOk checks for the include and exclude settings
if (!isFileNameOk(activeEditor.document.fileName)) {
    return;
}
```

**Comment by dienluong** [comment]
WOW!  I installed this just now (and the original extension two days ago) and the first thing I noticed was this huge and silly bug.  I'm very surprised that it was known for so long but never fixed. Also very surprised that the original extension got so many downloads, while half-baked.

**Comment by jgclark** [comment]
@yuriykis helpful PR is merged. Aiming to release later today.
