### ISSUE TITLE
wayou's extension seems to be maintained

### ISSUE THREAD

**Issue by memeplex** [jgclark/vscode-todo-highlight#43]
In your README you say wayou's extension is unmaintained but in the marketplace its last update date is:

10/29/2021, 12:31:46 AM

**Comment by jgclark** [comment]
You're correct. I was surprised to see the recent update after more than 2 years of no updates, despite lots of issues, requests, and even PRs. So I will leave the comment there for now, and remove if (as I hope) @wayou makes further updates.

**Comment by memeplex** [comment]
Updates are not by wayou and are pretty sparse though. I just pointed out this because the comment might be unfair to the new maintainer, in case there actually is one.

**Comment by jgclark** [comment]
I've now checked the commits (I thought I was subscribed to all activity but I wasn't). Most are from a Microsoft employee who is helping port all extensions to the web platform -- the same person has helped this fork. But a person with a similar handle has committed the PRs, so I've now updated the README as you suggest. Thanks.
