### ISSUE TITLE
I cannot set different background colors

### ISSUE THREAD

**Issue by Piero24** [jgclark/vscode-todo-highlight#59]
I tried to set different backgrounds on `todohighlight.defaultStyle` among here the null ones like `"transparent"`, `"none"`, `"rgba (0,0,0,0)"` and the colored ones but as you can see the result always remains the same. It only changes when I change the settings for the specific word.

<img width="288" alt="Screenshot 2022-10-29 at 10 42 53" src="https://user-images.githubusercontent.com/32714047/198823811-114307e4-2199-4233-a746-7f69066538c2.png">

**Comment by jgclark** [comment]
Does this still happen after reloading the file or trying the "Toggle Highlight" command twice (i.e. off and on)?
Have you checked to see if you have this set at another level in VSC (e.g. workspace / user / specific to a file type)?
If it's still not working, please post here all `todohighlight.*` settings from the JSON file.

**Comment by Piero24** [comment]
Resolved.
Yes, I tried the "Toggle Highlighting" command twice (ie off and on) but the problem continued.
I solved it with the following procedure:

1. Closed vscode
2. Cleaned the cache of the mac
3. restarted the mac
4. open a new project in vscode
5. changed the general colors of the highlights (i.e.)

```
"todohighlight.defaultStyle": {

        "backgroundColor": "rgba(0,0,0,0)",

    },
```

Now everything works correctly.
