### ISSUE TITLE
When displaying TODOs in Problems view, make then INFO level messages

### ISSUE THREAD

**Issue by auspex** [jgclark/vscode-todo-highlight#77]
I like to display my TODOs in the Problems view, and obviously as the setting to enable that is "Enable Diagnostics", that was never the primary focus of this extension. However, they're not _errors_. When they're tagged as errors, I can't filter them without hiding the serious issues I need to deal with.

It would be great to either always display them as Info, or to make the level configurable. I'm not sure if this is related to #1 or not. I would have thought #1 was accomplished with "Enable Diagnostics", so maybe I'm actually requesting what you've already proposed.

**Comment by auspex** [comment]
Yes, that seems to do what I want. Thanks!

Since it's a bit opaque, for anyone else wanting this, go to the Extension settings, find `Todohighlight: Keywords` and click on `Edit in settings.json`, then add `"diagnosticSeverity": "information",` to any or all of the keywords

**Comment by jgclark** [comment]
Thanks for checking. I'll update the documentation to properly include it.

**Comment by jgclark** [comment]
Completed.
