### ISSUE TITLE
Extension isn't working

### ISSUE THREAD

**Issue by morninj** [jgclark/vscode-todo-highlight#84]
I can't get this extension to work in VS Code v1.80.1 (the latest release as of today). I've tried every troubleshooting step I can think of, including:

- Enabling the extension
- Restarting VS Code
- Checking extension settings
- Checking for conflicting settings in `settings.json`
- Disabling all other extensions
- Confirming that the language modes are correctly set
- Reinstalling the extension
- Testing TODO highlighting in several different .js and .html files

**Comment by Unequaled804** [comment]
Please check if your file format is the Todohighlist Include list. For example if you are using a *.vue file, it maybe not on the default list.

**Comment by morninj** [comment]
Yep--I tried it on .js, .css, .html, and .py files.

**Comment by jgclark** [comment]
This minimal setting file does work for me. Obviously without further customisation it will only highlight `TODO:` and `FIXME:` strings, which are the only built-in ones. What are you trying to highlight?

**Comment by morninj** [comment]
Ah--I figured it out. I was writing `TODO` (no colon), but the default keyword matching only works for `TODO:` and `FIXME:` (with colons). Thanks for the help!
