### ISSUE TITLE
Use Settings UI

### ISSUE THREAD

**Issue by jgclark** [jgclark/vscode-todo-highlight#9]
A user has suggested it would be ideal if some of the settings could be controlled by the main VSC settings UI.
I think this will be too difficult for the advanced cases, but it might be possible for a simple list of keywords.

**Comment by ctf0** [comment]
the `defaultStyle` could use some rework too, ex. toggling `isWholeLine`

**Comment by jgclark** [comment]
@ctf0, thanks, but I don't understand what you're suggesting. Please expand.

**Comment by ctf0** [comment]
i mean
https://github.com/jgclark/vscode-todo-highlight/blob/7ba3783825ddf16c1cc94d88ec4435dbfd4550ef/package.json#L156-L173

doesnt have all the allowed/avail options & u have to go through the rdme to figure what if something like `isWholeLine` could be added under `todohighlight.defaultStyle` or not.

**Comment by jgclark** [comment]
The relevant documentation appears to be https://code.visualstudio.com/api/references/contribution-points.

**Comment by jgclark** [comment]
@ctf0 I've added `isWholeLine` to `defaultStyle` but that's the only extra one I can see could be added. All the others seem to be objects or arrays.  Will release an update in a few days, unless you spot something else that can be supported by VSC in the UI Settings page.

**Comment by jgclark** [comment]
Found a way to include the `exclude` and `include` settings in the UI Settings page, and am about to release as v2.0.1. That's the limits of what's possible, so now closing this issue.
