### ISSUE TITLE
Highlight only till the task description ends rather than the whole line

### ISSUE THREAD

**Issue by Aditi002-holo** [jgclark/vscode-todo-highlight#91]
Hi,

I have been using this extension for a while and discovered there is an option called "isWholeLine" which we can enable but that enables BG color to the whole line which can seem a little out of the place when going through the code (see image below).

Feature:
Can we build a feature where background color can be enabled only for the words/the sentence?

<img width="648" alt="todo-highlight" src="https://github.com/jgclark/vscode-todo-highlight/assets/96046912/14c44763-2c91-42ca-a6dd-15f508d35f36">

Thanks
Aditi

**Comment by jgclark** [comment]
"isWholeLine" works well where you really need something to stand out.
Background color will just be applied to the words/sentence that the regex
defines if "isWholeLine" is off. So I'm not sure what new feature is
required. Please elaborate if I have missed something.

**Comment by Anisotropic** [comment]
@jgclark Hi. Is it possible to mark only the commented part, not the whole line? Just like it works in Webstorm?
![image](https://github.com/jgclark/vscode-todo-highlight/assets/3103909/37484047-e460-4d99-8a40-8e1fa7a0fd8f)

**Comment by jgclark** [comment]
Background color will just be applied to the words that the regex defines if "isWholeLine" is off.
