### ISSUE TITLE
The scrollbar ruler is very messy, can I configure to diable it

### ISSUE THREAD

**Issue by Tobepeter** [jgclark/vscode-todo-highlight#92]
![CleanShot 2024-03-25 at 19 31 42@2x](https://github.com/jgclark/vscode-todo-highlight/assets/34265941/7c8b3a93-d7bd-4656-bf39-febd17deedb3)

I cannot found where to disable the that behavior by vscode settings

**Comment by jgclark** [comment]
Use the 'overviewRulerColor' setting to change the colours shown, or 'transparent' to turn off.
