### ISSUE TITLE
I just want an border frame.

### ISSUE THREAD

**Issue by FPXjunzhu** [jgclark/vscode-todo-highlight#96]
I just want an border frame. I don't want to change the original color of the code.
My code original like this:
![image](https://github.com/jgclark/vscode-todo-highlight/assets/173145602/08dcf09a-6022-4385-a90d-39150d6acb1b)

My setting.json like is:
`"todohighlight.defaultStyle": {
		"border": "1px solid #eee",
		"borderRadius": "2px", 
		"isWholeLine": false,
	},`
My code like this:
![image](https://github.com/jgclark/vscode-todo-highlight/assets/173145602/e2e07af8-5a88-4f11-8fc0-9cebf79ee45b)

If I set it like this
`"todohighlight.defaultStyle": {
		"backgroundColor": "rgba(255, 255, 0, 0)",
		"overviewRulerColor": "rgba(255, 255, 0, 0.1)",
		"border": "1px solid #eee",
		"borderRadius": "2px", 
		"isWholeLine": false,
	},`

And, My code like this:
![image](https://github.com/jgclark/vscode-todo-highlight/assets/173145602/211df071-9a49-45a9-afd6-2cdd8f14a511)

So, what should I do?

**Comment by jgclark** [comment]
I don't think you have shown all your settings, because by default that text won't be highlighted.
But it does seem that it currently changes the colour of the text to blue when a "color" isn't specified. I'd not found this edge case before.

A PR to fix this would be welcome.

**Comment by FPXjunzhu** [comment]
> I don't think you have shown all your settings, because by default that text won't be highlighted.
> But it does seem that it currently changes the colour of the text to blue when a "color" isn't specified. I'd not found this edge case before.
> 
> A PR to fix this would be welcome.

OK, Fine. I'll try fix it.

**Comment by cuiwanzhi** [comment]
I review the code. And I find way.
Just need setting like this:
`		"color": "",
		"backgroundColor": "",`
That overwrite DEFAULT_STYLE.
The code like this:
![image](https://github.com/user-attachments/assets/3d8281db-e62c-4f5f-8cc7-837cac2ba265)


Last, I have a question. @jgclark 
Why are defind the DEFAULT_STYLE in package.json?
![image](https://github.com/user-attachments/assets/0bb992ee-9b95-42e4-8401-845559bc1d79)
![image](https://github.com/user-attachments/assets/ba6dd055-0689-44f9-ba05-e987b56c79a8)

**Comment by jgclark** [comment]
> Last, I have a question. @jgclark
> Why are defind the DEFAULT_STYLE in package.json?

Because then TODO: and FIXME: will work as soon as you turn the extension on, without needing users to work out how to configure the colour codes. 
But it can be over-ridden (as you have done) when a user decides to learn more about it.
